default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: vantaggio_development
  username: dhiogo
  password: 123456

test:
  <<: *default
  database: vantaggio_test
  username: dhiogo
  password: 123456

production:
  <<: *default
  database: vantaggio_production
  username: vantaggio
  password: vantaggio123
