default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PG_HOST", "localhost") %>
  port: <%= ENV.fetch("PG_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("PG_DATABASE") %>
  username: <%= ENV.fetch("PG_USERNAME") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>

test:
  <<: *default

production:
  <<: *default

